### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by ad3429** [spiercy64/intro-data-capstone-biodiversity#5]
**Summary Grade: Satisfactory**

Good job overall! Your slides are short and to the point, and you made sure to include relevant graphs and charts when appropriate.

Your recommendations and conclusions are valid, however it would be good to include more calculations – for example, in the section where you describe the significance calculations that you did for endangered status between different categories of species, there was no mention of your calculated p-value or how you got that value This would give more authority to your statements, and should be included in your presentation.

Overall, you did a great job with your findings and your suggestions and recommendations are statistically valid. It's clear that you've been growing as a data scientist, so I would make sure to keep up the good work!

**Comment by spiercy64** [comment]
Thankyou for the feedback, I was cutting it a bit fine on getting it on time, shall add more of the calculations next time.
